### ISSUE TITLE
add Menu component

### ISSUE THREAD

**Issue by wahyufeb** [qwikifiers/qwik-ui#216] opened 2023-02-26 13:16 UTC

**Comment by wahyufeb** [comment] 2023-02-26 13:22
Hi @gioboa, I will work on this.

**Comment by gioboa** [comment] 2023-02-26 13:46
Menu component is already present, am I wrong?

**Comment by wahyufeb** [comment] 2023-02-26 13:55
The menu show like this 
https://daisyui.com/components/menu/

It's like a Dropdown but has a submenu inside it

**Comment by gioboa** [comment] 2023-02-27 17:14
So your implementation will be a variant of the menu component, right?

**Comment by gioboa** [comment] 2023-02-27 17:15
is it a duplicate of [this issue](https://github.com/qwikifiers/qwik-ui/issues/160)?

**Comment by wahyufeb** [comment] 2023-02-28 02:38
> is it a duplicate of [this issue](https://github.com/qwikifiers/qwik-ui/issues/160)?

I think so, I will work on that😃

**Closed** 2024-05-31 12:46 UTC
